### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by Swall0w** [Swall0w/arxiv-bot#7]
Pack your bags, we’re taking you to 52 places in 2018 https://t.co/G10ETN3KPe https://t.co/Ob9ZLoqWrJ
The New York Times(nytimes) 2018-01-12 04:22:19 via SocialFlow

Traceback (most recent call last):
  File "main.py", line 62, in <module>
    main()
  File "main.py", line 58, in main
    stream.userstream()
  File "/home/masato/anaconda3/lib/python3.5/site-packages/tweepy/streaming.py", line 394, in userstream
    self._start(async)
  File "/home/masato/anaconda3/lib/python3.5/site-packages/tweepy/streaming.py", line 361, in _start
    self._run()
  File "/home/masato/anaconda3/lib/python3.5/site-packages/tweepy/streaming.py", line 294, in _run
    raise exception
  File "/home/masato/anaconda3/lib/python3.5/site-packages/tweepy/streaming.py", line 263, in _run
    self._read_loop(resp)
  File "/home/masato/anaconda3/lib/python3.5/site-packages/tweepy/streaming.py", line 313, in _read_loop
    line = buf.read_line().strip()
AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by Swall0w** [comment]
Another error occurerd.
```
Afghan officials said that meetings were underway in Turkey between their government and representatives of the Tal… https://t.co/fjfszdHUH1
The New York Times(nytimes) 2018-01-15 01:00:19 via SocialFlow

Traceback (most recent call last):
  File "main.py", line 67, in <module>
    main()
  File "main.py", line 63, in main
    stream.userstream()
  File "/home/masato/anaconda3/lib/python3.5/site-packages/tweepy/streaming.py", line 394, in userstream
    self._start(async)
  File "/home/masato/anaconda3/lib/python3.5/site-packages/tweepy/streaming.py", line 361, in _start
    self._run()
  File "/home/masato/anaconda3/lib/python3.5/site-packages/tweepy/streaming.py", line 294, in _run
    raise exception
  File "/home/masato/anaconda3/lib/python3.5/site-packages/tweepy/streaming.py", line 263, in _run
    self._read_loop(resp)
  File "/home/masato/anaconda3/lib/python3.5/site-packages/tweepy/streaming.py", line 313, in _read_loop
    line = buf.read_line().strip()
AttributeError: 'NoneType' object has no attribute 'strip'
```
